export const POPULATE_ARTICLES = 'POPULATE_ARTICLES'
export const POPULATE_COMMENTS = 'ADD_COMMENTS'
export const ADD_ARTICLE = 'ADD_ARTICLE'
export const ADD_COMMENT = 'ADD_COMMENT'

export const SET_FILTER_DATE_FROM = 'SET_FILTER_DATE_FROM'
export const SET_FILTER_DATE_TILL = 'SET_FILTER_DATE_TILL'
